/*
 * Type definitions related to products.
 */

/**
 * A single product in the store.
 *
 * Money handling note:
 * We store the price as an integer number of CENTS (for example 1299 means
 * $12.99), never as a decimal like 12.99. Decimal numbers can lose precision
 * during math in JavaScript (0.1 + 0.2 is not exactly 0.3), so working in whole
 * cents keeps every calculation exact. We only convert to dollars when we show
 * the price on screen.
 */
export interface Product {
  id: string;
  name: string;
  description: string;
  /** Price in whole cents. Example: 1299 means $12.99. */
  priceCents: number;
  /** How many units are available to buy. */
  stock: number;
  /** Web address of the product image. */
  imageUrl: string;
  /** A grouping label such as "Electronics" used by the category filter. */
  category: string;
  /** A rating from 0 to 5. */
  rating: number;
  /** Stock Keeping Unit: a unique code that identifies the product. */
  sku: string;
}

/*
 * ==========================================================================
 * ApiProduct: the RAW shape returned by the backend database / API.
 * ==========================================================================
 *
 * This matches the real backend EXACTLY. The mock service stores its data in
 * this shape, so that when we later swap the mock for real HTTP calls, the data
 * arriving from the server already has the same structure and nothing else in
 * the app has to change.
 *
 * Notice how it differs from the clean Product type above:
 *   - Field names are snake_case: product_id, price_amount, image_url.
 *   - price_amount is a STRING that holds cents. Example: "1975" means $19.75.
 *   - "inventory" is what the rest of the app calls "stock".
 *   - "rating" is nested inside the "meta" object.
 *
 * The function mapApiProductToProduct() in utils/productMapper.ts turns an
 * ApiProduct into the friendlier Product shape the rest of the app uses.
 */

/** The nested "meta" object inside an ApiProduct. */
export interface ApiProductMeta {
  brand: string;
  specs: {
    model: string;
    warranty_months: number;
  };
  rating: number;
  category: string;
  featured: boolean;
}

/** One product exactly as the backend database returns it. */
export interface ApiProduct {
  product_id: string;
  name: string;
  description: string;
  sku: string;
  category: string;
  /** Price in cents, stored as a STRING. Example: "1975" means $19.75. */
  price_amount: string;
  /** Units in stock. The rest of the app calls this "stock". */
  inventory: number;
  image_url: string;
  meta: ApiProductMeta;
}

/**
 * The data needed to CREATE or UPDATE a product.
 *
 * This is the same as a Product but without the "id", because the id is
 * generated by the service when the product is first created and never changes
 * afterwards.
 */
export interface ProductInput {
  name: string;
  description: string;
  priceCents: number;
  stock: number;
  imageUrl: string;
  category: string;
  rating: number;
  sku: string;
}

/**
 * The options we can pass when asking the service for a list of products.
 * Every field is optional so the caller can provide only what it needs.
 */
export interface ProductQuery {
  /** Text typed into the search box. Matches product name or description. */
  search?: string;
  /** Only return products in this category. */
  category?: string;
  /** Which page of results to return (starting at 1). */
  page?: number;
  /** How many products to show per page. */
  pageSize?: number;
}

/**
 * The shape of a paged list of products returned by the service.
 *
 * We return both the items for the current page AND the total count, because
 * the pagination control needs to know the total to figure out how many pages
 * there are.
 */
export interface ProductPage {
  items: Product[];
  total: number;
  page: number;
  pageSize: number;
}
